<?php
/**
 * Koren Software
 *
 * @package    Koren_SimpleCmsMenu
 * @author     Koren Software
 * @copyright  Copyright (c) 2020 Koren Software. (https://koren.ee)
 * @license    MIT
 */

$pages = $block->getPages();

if (count($pages) > 0) {
    echo '<div class="submenu">';
    echo '<ul class="links">';
    foreach ($pages as $page) {
        echo '<li'.($page->isActive() ? ' class="active"' : '').'><a href="/'./** @noEscape */$page->getIdentifier().'">'./** @noEscape */$page->getTitle().'</a></li>';
    }
    echo '</ul>';
    echo '</div>';
}
